### ISSUE TITLE
Pinchar en cada dentro desde la lista de centros

### ISSUE THREAD

**Issue by Lu-pando** [s-nt-s/centros#4]
En la vista del listado de centros, no se puede hacer clic para ver en determinado centro, no vendría mal, para, por ejemplo, ver dónde está en el mapa.

**Comment by s-nt-s** [comment]
Si no te he entendido mal, esa función ya esta implementada. Esto es lo que hace actualmente la página:

![captura gif](https://github.com/s-nt-s/centros/assets/5998601/ad34bc00-e2d7-4f66-a7ed-6ee8e202d3b4)

¿Desde que explorador y dispositivo estas visitante la página?

**Comment by Lu-pando** [comment]
Ahh! Desde Chrome en móvil, por eso no me salía, gracias!

**Comment by s-nt-s** [comment]
Desde Chrome en móvil también me funciona.
